const TT_DATA = {
 "entries": [
  {
   "day": "MON",
   "time": "9-10AM",
   "type": "L",
   "elective": false,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "BT413",
   "room": "G5",
   "faculty": "ASM,AKV",
   "raw": "LC1-C3(BT413)-G5 /ASM,AKV"
  },
  {
   "day": "MON",
   "time": "1-2PM",
   "type": "L",
   "elective": false,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "BT311",
   "room": "CS1",
   "faculty": "VGU,SBT",
   "raw": "LC1-C3 (BT311)- CS1/VGU,SBT"
  },
  {
   "day": "MON",
   "time": "11-12PM",
   "type": "L",
   "elective": false,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "HS311",
   "room": "CS3",
   "faculty": "YN",
   "raw": "LC1,C2,C3 (HS311)- CS3/YN"
  },
  {
   "day": "MON",
   "time": "2-3PM",
   "type": "T",
   "elective": false,
   "batches": ["C2"],
   "deptLetters": ["C"],
   "course": "BT311",
   "room": "TS12",
   "faculty": "VGU,SBT",
   "raw": "TC2(BT311)- TS12/VGU,SBT"
  },
  {
   "day": "MON",
   "time": "10-11AM",
   "type": "T",
   "elective": false,
   "batches": ["C1"],
   "deptLetters": ["C"],
   "course": "BT413",
   "room": "TS12",
   "faculty": "ASM,AKV",
   "raw": "TC1 (BT413)- TS12/ASM,AKV"
  },
  {
   "day": "MON",
   "time": "12-1PM",
   "type": "L",
   "elective": false,
   "batches": ["minor"],
   "deptLetters": [],
   "course": "24B11CS351",
   "room": "CS1",
   "faculty": "MON",
   "raw": "Lminor(24B11CS351)-CS1/ MON"
  },
  {
   "day": "MON",
   "time": "12-1PM",
   "type": "L",
   "elective": false,
   "batches": ["minor"],
   "deptLetters": [],
   "course": "24B11CS353",
   "room": "CS3",
   "faculty": "AMS",
   "raw": "Lminor(24B11CS353)-CS3/AMS"
  },
  {
   "day": "TUES",
   "time": "8-9AM",
   "type": "SE1",
   "elective": true,
   "batches": [],
   "deptLetters": [],
   "course": "",
   "room": "",
   "faculty": "",
   "elective_choice": "2",
   "raw": "SE1/2"
  },
  {
   "day": "TUES",
   "time": "9-10AM",
   "type": "DE2",
   "elective": true,
   "batches": [],
   "deptLetters": [],
   "course": "",
   "room": "",
   "faculty": "",
   "elective_choice": "2",
   "raw": "DE2/2"
  },
  {
   "day": "TUES",
   "time": "12-1PM",
   "type": "L",
   "elective": false,
   "batches": ["minor"],
   "deptLetters": [],
   "course": "PH412",
   "room": "FF8",
   "faculty": "RKG",
   "raw": "Lminor(PH412)-FF8/RKG"
  },
  {
   "day": "TUES",
   "time": "4-5PM",
   "type": "P",
   "elective": false,
   "batches": ["minor"],
   "deptLetters": [],
   "course": "24B15CS352",
   "room": "CL22",
   "faculty": "NEH",
   "raw": "Pminor(24B15CS352)-CL22/ NEH"
  },
  {
   "day": "TUES",
   "time": "4-5PM",
   "type": "P",
   "elective": false,
   "batches": ["minor"],
   "deptLetters": [],
   "course": "24B15CS354",
   "room": "CL23",
   "faculty": "AMS",
   "raw": "Pminor(24B15CS354)-CL23/ AMS"
  },
  {
   "day": "TUES",
   "time": "12-1PM",
   "type": "L",
   "elective": false,
   "batches": ["minor"],
   "deptLetters": [],
   "course": "24B11CS351",
   "room": "CS3",
   "faculty": "MON",
   "raw": "Lminor(24B11CS351)-CS3/ MON"
  },
  {
   "day": "TUES",
   "time": "12-1PM",
   "type": "L",
   "elective": false,
   "batches": ["minor"],
   "deptLetters": [],
   "course": "24B11CS353",
   "room": "CS4",
   "faculty": "AMS",
   "raw": "Lminor(24B11CS353)-CS4/AMS"
  },
  {
   "day": "TUES",
   "time": "1-2PM",
   "type": "L",
   "elective": false,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "HS311",
   "room": "CS3",
   "faculty": "YN",
   "raw": "LC1,C2,C3 (HS311)- CS3/YN"
  },
  {
   "day": "TUES",
   "time": "10-11AM",
   "type": "L",
   "elective": false,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "BT311",
   "room": "G9",
   "faculty": "VGU,SBT",
   "raw": "LC1-C3 (BT311)- G9/VGU,SBT"
  },
  {
   "day": "TUES",
   "time": "11-12PM",
   "type": "T",
   "elective": false,
   "batches": ["C3"],
   "deptLetters": ["C"],
   "course": "BT311",
   "room": "TS12",
   "faculty": "VGU,SBT",
   "raw": "TC3(BT311)- TS12/VGU,SBT"
  },
  {
   "day": "TUES",
   "time": "8-9AM",
   "type": "L",
   "elective": true,
   "batches": ["A1","A2","A3","A4","A5","A6","A7","A8","A10","A15","A16","A17","A18","C1","C2","C3"],
   "deptLetters": ["A","C"],
   "course": "16B1NMA531",
   "room": "CR401",
   "faculty": "NF2",
   "raw": "LAC(16B1NMA531)-CR401/NF2"
  },
  {
   "day": "TUES",
   "time": "8-9AM",
   "type": "L",
   "elective": true,
   "batches": ["A1","A2","A3","A4","A5","A6","A7","A8","A10","A15","A16","A17","A18","B1","B2","B3","B4","B5","B6","B7","B8","B9","B10","B11","B12","B13","B14","C1","C2","C3"],
   "deptLetters": ["A","B","C"],
   "course": "16B1NMA533",
   "room": "CR425",
   "faculty": "MKB",
   "raw": "LABC(16B1NMA533)-CR425/MKB"
  },
  {
   "day": "TUES",
   "time": "8-9AM",
   "type": "L",
   "elective": true,
   "batches": ["A1","A2","A3","A4","A5","A6","A7","A8","A10","A15","A16","A17","A18","B1","B2","B3","B4","B5","B6","B7","B8","B9","B10","B11","B12","B13","B14","C1","C2","C3"],
   "deptLetters": ["A","B","C"],
   "course": "17B1NMA531",
   "room": "CR526",
   "faculty": "NF5",
   "raw": "LABC(17B1NMA531)-CR526/NF5"
  },
  {
   "day": "TUES",
   "time": "9-10AM",
   "type": "L",
   "elective": true,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "26BT312",
   "room": "FF8",
   "faculty": "MOB",
   "raw": "LC(26BT312)-FF8/MOB"
  },
  {
   "day": "TUES",
   "time": "9-10AM",
   "type": "L",
   "elective": true,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "26BT314",
   "room": "FF9",
   "faculty": "KAR",
   "raw": "LC(26BT314)-FF9/KAR"
  },
  {
   "day": "WED",
   "time": "9-10AM",
   "type": "DE3",
   "elective": true,
   "batches": [],
   "deptLetters": [],
   "course": "",
   "room": "",
   "faculty": "",
   "elective_choice": "1",
   "raw": "DE3/1"
  },
  {
   "day": "WED",
   "time": "12-1PM",
   "type": "L",
   "elective": false,
   "batches": ["minor"],
   "deptLetters": [],
   "course": "PH412",
   "room": "FF8",
   "faculty": "RKG",
   "raw": "Lminor(PH412)-FF8/RKG"
  },
  {
   "day": "WED",
   "time": "4-5PM",
   "type": "P",
   "elective": false,
   "batches": ["minor"],
   "deptLetters": [],
   "course": "24B15CS354",
   "room": "CL21",
   "faculty": "AMS",
   "raw": "Pminor(24B15CS354)-CL21/ AMS"
  },
  {
   "day": "WED",
   "time": "10-11AM",
   "type": "T",
   "elective": false,
   "batches": ["C2"],
   "deptLetters": ["C"],
   "course": "BT413",
   "room": "TS12",
   "faculty": "ASM,AKV",
   "raw": "TC2 (BT413)- TS12/ASM,AKV"
  },
  {
   "day": "WED",
   "time": "10-11AM",
   "type": "P",
   "elective": false,
   "batches": ["C3"],
   "deptLetters": ["C"],
   "course": "15BT311",
   "room": "BT2&3",
   "faculty": "SOC,SHM",
   "raw": "PC3(15BT311)/-BT2&3/ SOC,SHM"
  },
  {
   "day": "WED",
   "time": "10-11AM",
   "type": "P",
   "elective": false,
   "batches": ["C1"],
   "deptLetters": ["C"],
   "course": "18BT311",
   "room": "BT1",
   "faculty": "RPS,VGU",
   "raw": "PC1(18BT311)/-BT1/RPS,VGU"
  },
  {
   "day": "WED",
   "time": "12-1PM",
   "type": "L",
   "elective": false,
   "batches": ["minor"],
   "deptLetters": [],
   "course": "24B11CS351",
   "room": "CS3",
   "faculty": "MON",
   "raw": "Lminor(24B11CS351)-CS3/ MON"
  },
  {
   "day": "WED",
   "time": "12-1PM",
   "type": "L",
   "elective": false,
   "batches": ["minor"],
   "deptLetters": [],
   "course": "24B11CS353",
   "room": "CS4",
   "faculty": "AMS",
   "raw": "Lminor(24B11CS353)-CS4/AMS"
  },
  {
   "day": "WED",
   "time": "9-10AM",
   "type": "L",
   "elective": true,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "26BT315",
   "room": "CR401",
   "faculty": "POC",
   "raw": "LC(26BT315)-CR401/POC"
  },
  {
   "day": "WED",
   "time": "9-10AM",
   "type": "L",
   "elective": true,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "26BT313",
   "room": "CR425",
   "faculty": "ANM",
   "raw": "LC(26BT313)-CR425/ANM"
  },
  {
   "day": "THUR",
   "time": "8-9AM",
   "type": "DE3",
   "elective": true,
   "batches": [],
   "deptLetters": [],
   "course": "",
   "room": "",
   "faculty": "",
   "elective_choice": "2",
   "raw": "DE3/2"
  },
  {
   "day": "THUR",
   "time": "9-10AM",
   "type": "SE1",
   "elective": true,
   "batches": [],
   "deptLetters": [],
   "course": "",
   "room": "",
   "faculty": "",
   "elective_choice": "3",
   "raw": "SE1/3"
  },
  {
   "day": "THUR",
   "time": "12-1PM",
   "type": "L",
   "elective": false,
   "batches": ["minor"],
   "deptLetters": [],
   "course": "PH412",
   "room": "FF8",
   "faculty": "RKG",
   "raw": "Lminor(PH412)-FF8/RKG"
  },
  {
   "day": "THUR",
   "time": "3-4PM",
   "type": "L",
   "elective": false,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "BT413",
   "room": "CS3",
   "faculty": "ASM,AKV",
   "raw": "LC1-C3(BT413)- CS3/ASM,AKV"
  },
  {
   "day": "THUR",
   "time": "1-2PM",
   "type": "T",
   "elective": false,
   "batches": ["C1"],
   "deptLetters": ["C"],
   "course": "BT311",
   "room": "TS17",
   "faculty": "VGU,SBT",
   "raw": "TC1(BT311)- TS17/VGU,SBT"
  },
  {
   "day": "THUR",
   "time": "1-2PM",
   "type": "P",
   "elective": false,
   "batches": ["C3"],
   "deptLetters": ["C"],
   "course": "18BT311",
   "room": "BT1",
   "faculty": "APC,NV",
   "raw": "PC3(18BT311)/-BT1/APC,NV"
  },
  {
   "day": "THUR",
   "time": "1-2PM",
   "type": "P",
   "elective": false,
   "batches": ["C2"],
   "deptLetters": ["C"],
   "course": "15BT311",
   "room": "BT2&3",
   "faculty": "SOC,SHM",
   "raw": "PC2(15BT311)/-BT2&3/ SOC,SHM"
  },
  {
   "day": "THUR",
   "time": "9-10AM",
   "type": "L",
   "elective": true,
   "batches": ["A1","A2","A3","A4","A5","A6","A7","A8","A10","A15","A16","A17","A18","C1","C2","C3"],
   "deptLetters": ["A","C"],
   "course": "16B1NMA531",
   "room": "CR425",
   "faculty": "NF2",
   "raw": "LAC(16B1NMA531)-CR425/NF2"
  },
  {
   "day": "THUR",
   "time": "9-10AM",
   "type": "L",
   "elective": true,
   "batches": ["A1","A2","A3","A4","A5","A6","A7","A8","A10","A15","A16","A17","A18","B1","B2","B3","B4","B5","B6","B7","B8","B9","B10","B11","B12","B13","B14","C1","C2","C3"],
   "deptLetters": ["A","B","C"],
   "course": "16B1NMA533",
   "room": "FF7",
   "faculty": "MKB",
   "raw": "LABC(16B1NMA533)-FF7/MKB"
  },
  {
   "day": "THUR",
   "time": "10-11AM",
   "type": "L",
   "elective": false,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "BT311",
   "room": "LT3",
   "faculty": "VGU,SBT",
   "raw": "LC1-C3 (BT311)- LT3/VGU,SBT"
  },
  {
   "day": "THUR",
   "time": "8-9AM",
   "type": "L",
   "elective": true,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "26BT315",
   "room": "CR526",
   "faculty": "POC",
   "raw": "LC(26BT315)-CR526/POC"
  },
  {
   "day": "THUR",
   "time": "9-10AM",
   "type": "L",
   "elective": true,
   "batches": ["A1","A2","A3","A4","A5","A6","A7","A8","A10","A15","A16","A17","A18","B1","B2","B3","B4","B5","B6","B7","B8","B9","B10","B11","B12","B13","B14","C1","C2","C3"],
   "deptLetters": ["A","B","C"],
   "course": "17B1NMA531",
   "room": "FF9",
   "faculty": "NF5",
   "raw": "LABC(17B1NMA531)-FF9/NF5"
  },
  {
   "day": "THUR",
   "time": "8-9AM",
   "type": "L",
   "elective": true,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "26BT313",
   "room": "FF7",
   "faculty": "ANM",
   "raw": "LC(26BT313)-FF7/ANM"
  },
  {
   "day": "THUR",
   "time": "12-1PM",
   "type": "P",
   "elective": false,
   "batches": ["minor"],
   "deptLetters": [],
   "course": "24B15CS352",
   "room": "CL09",
   "faculty": "NEH",
   "raw": "Pminor(24B15CS352)-CL09/ NEH"
  },
  {
   "day": "FRI",
   "time": "8-9AM",
   "type": "SE1",
   "elective": true,
   "batches": [],
   "deptLetters": [],
   "course": "",
   "room": "",
   "faculty": "",
   "elective_choice": "1",
   "raw": "SE1/1"
  },
  {
   "day": "FRI",
   "time": "9-10AM",
   "type": "DE2",
   "elective": true,
   "batches": [],
   "deptLetters": [],
   "course": "",
   "room": "",
   "faculty": "",
   "elective_choice": "1",
   "raw": "DE2/1"
  },
  {
   "day": "FRI",
   "time": "3-4PM",
   "type": "L",
   "elective": false,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "HS311",
   "room": "G2",
   "faculty": "YN",
   "raw": "LC1,C2,C3 (HS311)- G2/YN"
  },
  {
   "day": "FRI",
   "time": "11-12PM",
   "type": "L",
   "elective": false,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "BT413",
   "room": "CS4",
   "faculty": "ASM,AKV",
   "raw": "LC1-C3(BT413)- CS4/ASM,AKV"
  },
  {
   "day": "FRI",
   "time": "8-9AM",
   "type": "L",
   "elective": true,
   "batches": ["A1","A2","A3","A4","A5","A6","A7","A8","A10","A15","A16","A17","A18","C1","C2","C3"],
   "deptLetters": ["A","C"],
   "course": "16B1NMA531",
   "room": "CR425",
   "faculty": "NF2",
   "raw": "LAC(16B1NMA531)-CR425/NF2"
  },
  {
   "day": "FRI",
   "time": "8-9AM",
   "type": "L",
   "elective": true,
   "batches": ["A1","A2","A3","A4","A5","A6","A7","A8","A10","A15","A16","A17","A18","B1","B2","B3","B4","B5","B6","B7","B8","B9","B10","B11","B12","B13","B14","C1","C2","C3"],
   "deptLetters": ["A","B","C"],
   "course": "16B1NMA533",
   "room": "CR501",
   "faculty": "MKB",
   "raw": "LABC(16B1NMA533)-CR501/MKB"
  },
  {
   "day": "FRI",
   "time": "10-11AM",
   "type": "T",
   "elective": false,
   "batches": ["C3"],
   "deptLetters": ["C"],
   "course": "BT413",
   "room": "TS12",
   "faculty": "ASM,AKV",
   "raw": "TC3 (BT413)- TS12/ASM,AKV"
  },
  {
   "day": "FRI",
   "time": "8-9AM",
   "type": "L",
   "elective": true,
   "batches": ["A1","A2","A3","A4","A5","A6","A7","A8","A10","A15","A16","A17","A18","B1","B2","B3","B4","B5","B6","B7","B8","B9","B10","B11","B12","B13","B14","C1","C2","C3"],
   "deptLetters": ["A","B","C"],
   "course": "17B1NMA531",
   "room": "FF4",
   "faculty": "NF5",
   "raw": "LABC(17B1NMA531)-FF4/NF5"
  },
  {
   "day": "FRI",
   "time": "1-2PM",
   "type": "P",
   "elective": false,
   "batches": ["C1"],
   "deptLetters": ["C"],
   "course": "15BT311",
   "room": "BT2&3",
   "faculty": "KAR,SHM",
   "raw": "PC1(15BT311)/-BT2&3/ KAR,SHM"
  },
  {
   "day": "FRI",
   "time": "1-2PM",
   "type": "P",
   "elective": false,
   "batches": ["C2"],
   "deptLetters": ["C"],
   "course": "18BT311",
   "room": "BT1",
   "faculty": "APC,RPS",
   "raw": "PC2(18BT311)/-BT1/APC,RPS"
  },
  {
   "day": "FRI",
   "time": "9-10AM",
   "type": "L",
   "elective": true,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "26BT312",
   "room": "FF9",
   "faculty": "MOB",
   "raw": "LC(26BT312)-FF9/MOB"
  },
  {
   "day": "FRI",
   "time": "9-10AM",
   "type": "L",
   "elective": true,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "26BT314",
   "room": "CR526",
   "faculty": "KAR",
   "raw": "LC(26BT314)-CR526/KAR"
  },
  {
   "day": "SAT",
   "time": "8-9AM",
   "type": "DE2",
   "elective": true,
   "batches": [],
   "deptLetters": [],
   "course": "",
   "room": "",
   "faculty": "",
   "elective_choice": "3",
   "raw": "DE2/3"
  },
  {
   "day": "SAT",
   "time": "9-10AM",
   "type": "DE3",
   "elective": true,
   "batches": [],
   "deptLetters": [],
   "course": "",
   "room": "",
   "faculty": "",
   "elective_choice": "3",
   "raw": "DE3/3"
  },
  {
   "day": "SAT",
   "time": "12-1PM",
   "type": "P",
   "elective": false,
   "batches": ["minor"],
   "deptLetters": [],
   "course": "24B15CS352",
   "room": "CL05",
   "faculty": "NEH",
   "raw": "Pminor(24B15CS352)-CL05/ NEH"
  },
  {
   "day": "SAT",
   "time": "9-10AM",
   "type": "L",
   "elective": true,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "26BT315",
   "room": "CR301",
   "faculty": "POC",
   "raw": "LC(26BT315)-CR301/POC"
  },
  {
   "day": "SAT",
   "time": "9-10AM",
   "type": "L",
   "elective": true,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "26BT313",
   "room": "CR325",
   "faculty": "ANM",
   "raw": "LC(26BT313)-CR325/ANM"
  },
  {
   "day": "SAT",
   "time": "8-9AM",
   "type": "L",
   "elective": true,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "26BT312",
   "room": "CR401",
   "faculty": "MOB",
   "raw": "LC(26BT312)-CR401/MOB"
  },
  {
   "day": "SAT",
   "time": "8-9AM",
   "type": "L",
   "elective": true,
   "batches": ["C1","C2","C3"],
   "deptLetters": ["C"],
   "course": "26BT314",
   "room": "CR425",
   "faculty": "KAR",
   "raw": "LC(26BT314)-CR425/KAR"
  }
 ],
 "faculty": {
  "AKV": "Dr. Ankisha Vijay",
  "ANM": "Dr Ankit Mathur",
  "AMS": "Dr. Amit Mishra",
  "APC": "Dr Apurv Chatrath",
  "ASM": "Dr.Ashwani Mathur",
  "KAR": "Dr Kareena",
  "MOB": "Dr Monika Bajpai",
  "NV": "Dr. Nivedita Mishra",
  "POC": "Dr. Pooja Choudhary",
  "RPS": "Dr. Rajnish P Singh",
  "SBT": "Dr Surabhi Tomar",
  "SHM": "Dr. Shalini Mani",
  "SOC": "Dr. Sonam Chawla",
  "VGU": "Dr Vibha Gupta",
  "RKG": "Dr. Radha Krishan Gopal",
  "MKB": "Dr. Manish Kumar Bansal",
  "NEH": "Ms. Neha",
  "YN": "Dr Yogita Naruka"
 },
 "subjects": {
  "24B11CS351": "Computer Vision Workshop",
  "24B11CS353": "Data Science and Data Analytics Workshop-2",
  "24B15CS352": "Computer Vision Workshop Lab",
  "24B15CS354": "Data Science and Data Analytics Workshop-2 Lab",
  "16B1NMA531": "Discrete Mathematics",
  "16B1NMA533": "Matrix Computations",
  "17B1NMA531": "Basic Numerical Methods",
  "18BT311": "Industrial Biotechnology Lab - I",
  "26BT312": "Biocompliance and Safety Standards",
  "26BT314": "Environmental Law: Science, Policy and Practice",
  "26BT315": "Food Process Engineering",
  "26BT313": "Molecular Oncology",
  "HS311": "Indian Constitution & Traditional Knowledge",
  "BT413": "Bioprocess Engineering",
  "15BT311": "Industrial Biotechnology Lab - I",
  "PH412": "Minor Bioinformatics",
  "20B13HS311": "Indian Constitution & Traditional Knowledge",
  "15B11BT413": "Bioprocess Engineering",
  "15B17BT472": "Genetic Engineering Lab",
  "18B15BT311": "Industrial Biotechnology Lab - I",
  "24B11BT311": "Genetic Engineering",
  "24B17BT311": "Summer Training-II (6 weeks)"
 },
 "batches": ["C1","C2","C3"],
 "electives": ["DE2","DE3","SE1","minor"],
 "elective_legend": {
  "MINOR": [
   {"code":"25B11BT311","name":"Structural Bioinformatics"},
   {"code":"25B17BT312","name":"PBL on Structural Bioinformatics"}
  ],
  "DE2": [
   {"code":"26B12BT314","name":"Environmental Law: Science, Policy and Practice","credits":3,"choice":1,"compulsory":true},
   {"code":"26B12BT312","name":"Biocompliance and Safety Standards","credits":3,"choice":2,"compulsory":false}
  ],
  "DE3": [
   {"code":"26B12BT315","name":"Food Process Engineering","credits":3,"choice":1,"compulsory":true},
   {"code":"26B12BT313","name":"Molecular Oncology","credits":3,"choice":2,"compulsory":false}
  ],
  "SE1": [
   {"code":"16B1NMA531","name":"Discrete Mathematics","credits":3,"choice":1,"compulsory":true},
   {"code":"16B1NMA533","name":"Matrix Computations","credits":3,"choice":2,"compulsory":false},
   {"code":"16B1NPH534","name":"Bio-Materials Science","credits":3,"choice":3,"compulsory":false},
   {"code":"17B1NMA531","name":"Basic Numerical Methods","credits":3,"choice":4,"compulsory":false}
  ]
 },
 "dept_batches": {"C":["C1","C2","C3"]},
 "bt311_by_type": {"P":"Industrial Biotechnology Lab - I","L":"Genetic Engineering","T":"Genetic Engineering"},
 "times": ["8-9AM","9-10AM","10-11AM","11-12PM","12-1PM","1-2PM","2-3PM","3-4PM","4-5PM","5-6PM"],
 "days": ["MON","TUES","WED","THUR","FRI","SAT"]
};